-- Create extensions schema
CREATE SCHEMA IF NOT EXISTS extensions;
GRANT USAGE ON SCHEMA extensions TO escrap;

-- Create escrap schema
CREATE SCHEMA escrap AUTHORIZATION escrap_admin;

GRANT USAGE ON SCHEMA escrap TO escrap;

GRANT SELECT ON ALL TABLES IN SCHEMA escrap TO escrap;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA escrap TO escrap_admin;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA escrap TO escrap;

ALTER DEFAULT PRIVILEGES IN SCHEMA escrap GRANT SELECT ON TABLES TO escrap;
ALTER DEFAULT PRIVILEGES IN SCHEMA escrap GRANT USAGE, SELECT ON SEQUENCES TO escrap;
ALTER DEFAULT PRIVILEGES IN SCHEMA escrap GRANT INSERT, UPDATE, DELETE ON TABLES TO escrap_admin;